### ISSUE TITLE
XMLString vs NumToStr

### ISSUE THREAD

**Issue by zeegin** [pintov/1c-fints#2]
https://github.com/pintov/1c-fints/blob/dd0f0b02d8f9a0e2bd16df03efae2c54afdc7771/src/FinTS-HBCI.bsl#L193-L199

`XMLString`?

https://its.1c.ru/db/v8std#content:763:hdoc

**Comment by pintov** [comment]
Для даты конечно нужно использовать XMLString.
В какой локали может сломаться Format(Value, "NZ=0; NG=")?

**Comment by zeegin** [comment]
Дробная часть может быть запятой или точной, в русском и английском например будет разница.

+ В тех, в которых не арабский цифры.

![изображение](https://user-images.githubusercontent.com/729213/70445110-0e030f00-1aac-11ea-89a0-7f0e338536d7.png)
![изображение](https://user-images.githubusercontent.com/729213/70445150-24a96600-1aac-11ea-97df-79c784ad3c4b.png)
![изображение](https://user-images.githubusercontent.com/729213/70445198-3b4fbd00-1aac-11ea-93cd-bc9d914ad951.png)

**Comment by pintov** [comment]
Большое спасибо! Исправлю!

**Comment by pintov** [comment]
Исправил.
